---

- name: Default machine setup
  hosts: everyone
  become: true
  gather_facts: false
  roles:
  - credentials
  - config
  - packages

- name: Ops machine setup
  hosts: ops
  become: true
  gather_facts: true
  roles:
  - credentials
  - config
  - packages
  - geerlingguy.docker
  - ops-settings


- name: Disk storage setup
  hosts: diskstorage
  become: true
  gather_facts: true
  roles:
  - credentials
  - config
  - packages
  - geerlingguy.samba
  - diskstorage-settings