---

- name: Ensure Projects
  ansible.builtin.file:
    path: /home/{{ default_user }}/Projects
    state: directory
    owner: "{{ default_user }}"
    mode: 700

- name: Ensure .ssh
  ansible.builtin.file:
    path: /home/{{ default_user }}/.ssh
    state: directory

- name: Keys1
  copy:
    dest: /home/{{ default_user }}/.ssh/homelab-docker.key.pub
    src: '../../../protected/keys/docker/homelab-docker.key.pub'
    mode: u=r,g=,o=
- name: Keys2
  copy:
    dest: /home/{{ default_user }}/.ssh/homelab-docker.key
    src: '../../../protected/keys/docker/homelab-docker.key'
    mode: u=r,g=,o=

- name: Git checkout main repo
  ansible.builtin.git:
    repo: 'git@github.com:k0eff/helmfile-home-lab.git'
    dest: /home/{{ default_user }}/Projects/helmfile-home-lab
    version: main
    key_file: /home/{{ default_user }}/.ssh/homelab-docker.key
    accept_newhostkey: true

- name: Git checkout protected repo
  ansible.builtin.git:
    repo: 'git@github.com:k0eff/helmfile-home-lab-protected.git'
    dest: /home/{{ default_user }}/Projects/helmfile-home-lab/protected
    version: main
    key_file: /home/{{ default_user }}/.ssh/homelab-docker.key
    accept_newhostkey: true
