---

- name: Install tools
  apt:
    pkg: 
      - git
      - cmake
      - python3-paramiko
      - dos2unix
    state: present
    update_cache: true

- git_config:
    name: core.autocrlf
    scope: global
    value: false

- name: Ensure Projects
  ansible.builtin.file:
    path: /home/{{ default_user }}/Projects
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: u=rw,g=,o=
    mode: 0700

- name: Ensure .ssh
  ansible.builtin.file:
    path: /home/{{ default_user }}/.ssh
    state: directory

- name: Ensure .docker
  ansible.builtin.file:
    path: /home/{{ default_user }}/.docker
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Docker
  copy:
    dest: /home/{{ default_user }}/.docker/config.json
    src: '../../../protected/docker/config.json'
    mode: u=rw,g=,o=
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Keys1
  copy:
    dest: /home/{{ default_user }}/.ssh/homelab-docker.key.pub
    src: '../../../protected/keys/docker/homelab-docker.key.pub'
    mode: u=r,g=,o=

- name: Keys2
  copy:
    dest: /home/{{ default_user }}/.ssh/homelab-docker.key
    src: '../../../protected/keys/docker/homelab-docker.key'
    mode: u=r,g=,o=

- name: Ensure git ignores crlf
  command: "git config --global core.autocrlf true"


- name: Add a host in the configuration
  community.general.ssh_config:
    host: "github.com"
    identity_file: "/home/{{ default_user }}/.ssh/homelab-docker.key"

- name: Git checkout main repo
  ansible.builtin.git:
    repo: 'git@github.com:k0eff/helmfile-home-lab.git'
    dest: /home/{{ default_user }}/Projects/helmfile-home-lab
    version: main
    key_file: /home/{{ default_user }}/.ssh/homelab-docker.key
    accept_newhostkey: true
    force: true
  ignore_errors: true

- name: Git checkout protected repo
  ansible.builtin.git:
    repo: 'git@github.com:k0eff/helmfile-home-lab-protected.git'
    dest: /home/{{ default_user }}/Projects/helmfile-home-lab/protected
    version: main
    key_file: /home/{{ default_user }}/.ssh/homelab-docker.key
    accept_newhostkey: true
    force: true
  ignore_errors: true


- name: Set helmfile permissions
  ansible.builtin.file:
    path: /home/{{ default_user }}/Projects/helmfile-home-lab
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    recurse: true
