---


- name: Resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 192.168.31.177
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      options edns0 trust-ad
      search .